import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'package:intl/intl.dart';
import '../models/invoice.dart';
import '../models/business.dart';
import '../models/order.dart';
import '../models/customer.dart';

class PdfInvoiceGenerator {
  Future<String> generateInvoice({required Invoice invoice, required Business business, OrderModel? order, required List<OrderItem> items, Customer? customer}) async {
    final pdf = pw.Document();
    final cf = NumberFormat.currency(symbol: business.currencySymbol, decimalDigits: 2);
    final td = items.map((i) => [i.productName, i.qty.toStringAsFixed(2), cf.format(i.unitPrice), cf.format(i.total)]).toList();

    pdf.addPage(pw.MultiPage(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.all(32),
      build: (context) => [
        pw.Header(level: 0, child: pw.Text(business.name, style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold))),
        if (business.address != null && business.address!.isNotEmpty) pw.Text(business.address!),
        if (business.phone != null && business.phone!.isNotEmpty) pw.Text('Phone: ${business.phone}'),
        if (business.email != null && business.email!.isNotEmpty) pw.Text('Email: ${business.email}'),
        if (business.vatNumber != null && business.vatNumber!.isNotEmpty) pw.Text('VAT: ${business.vatNumber}'),
        pw.SizedBox(height: 24),
        pw.Row(mainAxisAlignment: pw.MainAxisAlignment.spaceBetween, children: [
          pw.Expanded(child: pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
            pw.Text('INVOICE', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
            pw.Text('#${invoice.invoiceNumber}'),
            pw.Text('Date: ${DateFormat.yMMMMd().format(invoice.createdAt)}'),
            if (order != null) pw.Text('Payment: ${order.paymentMethod}'),
          ])),
          if (customer != null) pw.Expanded(child: pw.Container(padding: const pw.EdgeInsets.all(12), decoration: pw.BoxDecoration(border: pw.Border.all(color: PdfColors.grey400)), child: pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
            pw.Text('Bill To:', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
            pw.Text(customer.name),
            if (customer.address != null && customer.address!.isNotEmpty) pw.Text(customer.address!),
            if (customer.phone != null && customer.phone!.isNotEmpty) pw.Text(customer.phone!),
            if (customer.email != null && customer.email!.isNotEmpty) pw.Text(customer.email!),
          ]))),
        ]),
        pw.SizedBox(height: 32),
        pw.TableHelper.fromTextArray(headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 12), headerDecoration: const pw.BoxDecoration(color: PdfColors.grey300), cellAlignment: pw.Alignment.centerLeft, headers: ['Item', 'Qty', 'Unit Price', 'Total'], data: td, columnWidths: {0: const pw.FixedColumnWidth(2.0), 1: const pw.FixedColumnWidth(0.5), 2: const pw.FixedColumnWidth(1.0), 3: const pw.FixedColumnWidth(1.0)}),
        pw.SizedBox(height: 24),
        pw.Align(alignment: pw.Alignment.centerRight, child: pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.end, children: [
          if (order != null) ...[
            pw.Text('Subtotal: ${cf.format(order.subtotal)}'),
            if (order.discount > 0) pw.Text('Discount: ${cf.format(order.discount)}'),
            pw.Text('VAT (${(business.vatRate * 100).toStringAsFixed(1)}%): ${cf.format(order.taxAmount)}'),
            pw.Divider(),
            pw.Text('Total: ${cf.format(order.total)}', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
          ] else ...[
            pw.Text('Total: ${cf.format(items.fold(0.0, (s, i) => s + i.total))}', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
          ],
        ])),
        if (order != null && order.paymentMethod.isNotEmpty) pw.Text('Payment Method: ${order.paymentMethod}'),
        if (business.receiptFooter != null && business.receiptFooter!.isNotEmpty) pw.Text(business.receiptFooter!),
        pw.SizedBox(height: 40),
        pw.Center(child: pw.Text('Generated by SpiceDesk', style: pw.TextStyle(fontSize: 10, color: PdfColors.grey500))),
      ],
    ));

    final dir = await getTemporaryDirectory();
    final file = File('${dir.path}/invoice_${invoice.id}.pdf');
    await file.writeAsBytes(await pdf.save());
    return file.path;
  }
}
